### ISSUE TITLE
Fan speed controls 

### ISSUE THREAD

**Issue by ineedhungry** [libdyson-wg/ha-dyson#104]
Dyson fan is missing fan speed controls.  There are 4 fan speeds it would be nice to have that as a control.

**Comment by ineedhungry** [comment]
I added the device to the front end card and it has the controls for speed.  So really the ask is just to have it in the device controls for automations.

**Comment by dotvezz** [comment]
Hey @ineedhungry! Sorry for the late reply here, but I'm happy to report that fan speed control is fully supported! Feel free to check out the [Home Assistant docs for the fan integration](https://www.home-assistant.io/integrations/fan/).

For automations, you'll most likely want to use the `fan.set_percentage` service. For a simple example, here's a service call that sets my downstairs TP02 to 50% speed:

```yaml
service: fan.set_percentage
data: 
    entity_id: fan.downstairs
    percentage: 50
```
