### ISSUE TITLE
HA core beta 2024.3 log message `loaded_executor` event loop blocking

### ISSUE THREAD

**Issue by Anto79-ops** [libdyson-wg/ha-dyson#138]
hello Ben!

3 times a charm?

Just installed HA 2024.3 core beta, and when enabling this logging in config.yaml,

```
logger:
  default: info
  logs:
    homeassistant.loader: debug
 ```

acording bdraco, there is some event loop blocking for this integration from the following:

```2024-02-28 15:44:10.065 DEBUG (MainThread) [homeassistant.loader] Component dyson_local import took 0.314 seconds (loaded_executor=False)```

The loaded_executor issue is Importing X blocks the event loop for 0.949 seconds

CC'ed @bdraco if you need more information
