### ISSUE TITLE
2024.8.0 - async_forward_entry_setup warning in logs

### ISSUE THREAD

**Issue by RedNo7** [libdyson-wg/ha-dyson#175]
Hi,

Got this after updating to 2024.8.0 (only a warning until Jan - v2025.1)

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:151
First occurred: 08:41:17 (4 occurrences)
Last logged: 08:41:17

Detected code that calls async_forward_entry_setup for integration dyson_local with title: Pure Cool and entry_id: 1c3f95d046f740418d0b03b4d2504fdc, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
```

**Comment by danielgoepp** [comment]
Same here, but I have been getting this since the previous version too, I don't think it's new. I'm currently running 2024.7.4 with the same messages. Not urgent, as you point out, it will work for the rest of the year. But definitely needs to be addressed. A few other integrations I use have similar warnings.

**Comment by dbdavid44** [comment]
Same issue here as well:

<img width="1378" alt="image" src="https://github.com/user-attachments/assets/465e2f5c-80d5-4ee5-b9cc-3efed08578cc">

**Comment by dotvezz** [comment]
Hi everyone here! The latest release ([v1.4.0](https://github.com/libdyson-wg/ha-dyson/releases/tag/v1.4.0)) _should_ finally resolve these silly logs. Please feel free to tell me I'm wrong if it doesn't though! Thanks to @slyoldfox for the PR that resolves this.

**Comment by RedNo7** [comment]
yep that all went and this is in it;s place:
```yaml
Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan (documentation, issues)
First occurred: 20:34:55 (4 occurrences)
Last logged: 20:34:57

Entity None (<class 'custom_components.dyson_local.fan.DysonPureCoolEntity'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
Entity None (<class 'custom_components.dyson_local.fan.DysonPureCoolEntity'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
```

Shall I raise a different issue (not sure if it related or co-incidental)?
